import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRef, useState } from "react";
import { toBlob } from "html-to-image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const imageContent = useRef<HTMLDivElement>(null);

  const [text, setText] = useState("");

  const handleImage = (id: number) => {
    const image = imageContent.current;
    if (image) {
      image.style.backgroundImage = `url(https://picsum.photos/id/${id}/400/400)`;
    }
  };

  const handleShare = async () => {
    if(!imageContent || !imageContent.current) {
      return;
    }
    const newFile = await toBlob(imageContent.current, {
      style: {
        width: "400px",
        height: "400px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-end", 
        alignItems: "center", 
        borderRadius: "28px", 
        marginTop: "2rem", 
        overflow: "hidden", 
        margin: "0",
        padding: "0",
      },
    });

    if(!newFile) {
      return;
    }

    // if(navigator.canShare == undefined){
    //   downloadImage(newFile);
    //   return;
    // }

    const data = {
      files: [
        new File([newFile], "nuzlocke.png", {
          type: newFile.type
        })
      ],
      title: "Nuzlocke",
      text: "Nuzlocke"
    };

    try {
      //@ts-ignore
      if (!navigator.canShare(data)) {
        downloadImage(newFile);
      }
      //@ts-ignore
      await navigator.share(data);
    } catch (err) {
      alert(err);
    }
  };

  const downloadImage = (image: Blob) => {
    const a = document.createElement("a");
    a.href = URL.createObjectURL(image);
    a.download = "image.png";
    a.click();
  };



  return (
    <>
      <Head>
        <title>Bom dia Mamãe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Gerador de imagem para Mães</h1>
        <div className={styles.imageButtons}>
          <button onClick={() => handleImage(237)}>
            <Image
              src="https://picsum.photos/id/237/200/200"
              alt="img1"
              width={200}
              height={200}
            />
          </button>
          <button onClick={() => handleImage(236)}>
            <Image
              src="https://picsum.photos/id/236/200/200"
              alt="img1"
              width={200}
              height={200}
            />
          </button>
          <button onClick={() => handleImage(235)}>
            <Image
              src="https://picsum.photos/id/235/200/200"
              alt="img1"
              width={200}
              height={200}
            />
          </button>
          <button onClick={() => handleImage(234)}>
            <Image
              src="https://picsum.photos/id/234/200/200"
              alt="img1"
              width={200}
              height={200}
            />
          </button>
        </div>
        <div className={styles.text}>
          <input type="text" onChange={(e) => setText(e.target.value)} />
        </div>
        <div className={styles.imageBox} ref={imageContent}>
          <p>{
            text
            }</p>
          <div className={styles.cupom}>
            <p>use o cupom x no iFood</p>
          </div>
        </div>
        <button className={styles.share} onClick={handleShare}>
          Compartilhar
        </button>
      </main>
    </>
  );
}
